version: "3.9"
services:
  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    restart: always
    environment:
      INFLUX_DB: $INFLUX_DB  # nom de la base de données créée à l'initialisation d'InfluxDB
      INFLUXDB_USER: $INFLUXDB_USER  # nom de l'utilisateur pour gérer cette base de données
      INFLUXDB_USER_PASSWORD: $INFLUXDB_USER_PASSWORD  # mot de passe de l'utilisateur pour gérer cette base de données
    volumes:
      - /mnt/data/influxdb:/var/lib/influxdb:Z  # volume pour stocker la base de données InfluxDB
    ports:
      - 8086:8086

  telegraf:
    image: telegraf
    depends_on:
      - influxdb  # indique que le service influxdb est nécessaire
    container_name: telegraf
    restart: always
    links:
      - influxdb:influxdb
    tty: true
    #command: -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d
    volumes:
      - /sys:/sys
      - /proc:/proc
      - /etc:/etc
      - /dev/sda2 # Main disk
      - /mnt:/mnt # Data disk
      - /var/run/docker.sock:/var/run/docker.sock:ro  # necessaire pour remonter les donnees du demon Docker
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro  # fichier de configuration de Telegraf

  grafana:
    image: grafana/grafana
    depends_on:
      - influxdb  # indique que le service influxdb est nécessaire
    container_name: grafana
    restart: always
    ports:
      - 3000:3000  # port pour accéder à l'interface web de Grafana
    user: "root"
    links:
      - influxdb:influxdb
    environment:
      GF_INSTALL_PLUGINS: "grafana-clock-panel,\
                          grafana-influxdb-08-datasource,\
                          grafana-kairosdb-datasource,\
                          grafana-piechart-panel,\
                          grafana-simple-json-datasource,\
                          grafana-worldmap-panel"
      GF_SECURITY_ADMIN_USER: $GF_SECURITY_ADMIN_USER  # nom de l'utilisateur créé par défaut pour accéder à Grafana
      GF_SECURITY_ADMIN_PASSWORD: $GF_SECURITY_ADMIN_PASSWORD  # mot de passe de l'utilisateur créé par défaut pour accéder à Grafana
    volumes:
      - /mnt/data/grafana_data:/var/lib/grafana:Z

  offline_map:
    image: store/klokantech/openmaptiles-server-dev:1.4-free
    container_name: osm_offline_map
    volumes:
      - /mnt/data/osm_maps/osm.mbtiles:/data/osm.mbtiles
    ports:
      - 8080:80